[versions]
kotlin = "2.0.21"
protobuf = "4.28.3"
jsonSchema = "1.5.2"
jackson = "2.18.1"
junit = "5.11.3"
junitPlatform = "1.11.3"
clikt = "5.0.1"
slf4j = "2.0.16"
protobufPlugin = "0.9.4"
grpc = "1.68.1"
tomcatAnnotations = "6.0.53"

[libraries]
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
jsonschema-validator = { module = "com.networknt:json-schema-validator", version.ref = "jsonSchema" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-inprocess = { module = "io.grpc:grpc-inprocess", version.ref = "grpc" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
tomcat-annotations = { module = "org.apache.tomcat:annotations-api", version.ref = "tomcatAnnotations" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }

[plugins]
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
